name: tag_and_release
on:
  pull_request:
   types: [closed]
jobs:
  push_tag_and_new_release:
#   && github.ref == 'develop' could be adjusted to 
#  && contains('
#        main,
#        develop
#      ', github.ref)
#, and then we'd automate releases for PRs merged to main also.
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'develop' 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Bump the version and push the tag
      id: bump_tag
      uses: ivanpk/github-tag-action@patch-prerelease #test my patch
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main # signals that the PR being merged to develop, should have the prerelease_suffix
        TAG_CONTEXT: repo 
        PRERELEASE_SUFFIX: rc
        VERBOSE: true
        
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v2.1.0
      with:
          configuration: ".github/workflows/release-changelog-config.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.bump_tag.outputs.new_tag }}
        release_name: ${{ steps.bump_tag.outputs.new_tag }}
        body: ${{steps.build_changelog.outputs.changelog}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
